name: 🚀 Feature Request
description: Suggest a new feature for webdev-power-kit
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      placeholder: What would you like to see added?
    validations:
      required: true

  - type: input
    id: use-case
    attributes:
      label: Why do you need this feature?
      placeholder: Example: I want to detect screen rotation.
    validations:
      required: true

  - type: checkboxes
    id: context
    attributes:
      label: Feature Category
      options:
        - label: Browser API
        - label: Utility Tool
        - label: Performance Helper
        - label: Device Info
        - label: Other
