name: "🚀 Feature Request"
description: Suggest a new feature for webdev-power-kit
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        💡 Thanks for contributing! Please describe your requested feature below.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to see added? Be specific and clear.
      placeholder: e.g. A function that returns the current screen orientation.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Why do you need this feature?
      description: What’s your use case or what problem would this feature solve?
      placeholder: e.g. I want to change layout when screen rotates on mobile.
    validations:
      required: true

  - type: checkboxes
    id: category
    attributes:
      label: Related Category
      description: Which category does this feature belong to?
      options:
        - label: 📦 Browser API
        - label: 🛠 Utility Tool
        - label: 📊 Performance
        - label: 📱 Device Info
        - label: 🔍 Other / Not Sure
